sudo: required
language: python
services:
- docker
python:
- '3.6'
install:
- pip install -r requirements.txt
- bundle install
script: bundle exec kitchen test
after_script:
  - bundle exec kitchen list all
  - bundle exec kitchen destroy all